In [1]:
import tensorflow as tf

In [12]:
a = tf.constant(2)
b = tf.constant(3)
c = a + b
c

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [5]:
sess = tf.Session()
sess.run(c)

5

In [21]:
a1 = tf.constant([[1,2], [3,4]])
a2 = tf.constant([[2,2], [3,3]])
res = tf.matmul(a1, a2)
result, resc = sess.run([res, c])
result, resc

(array([[ 8,  8],
        [18, 18]], dtype=int32), 5)

In [26]:
#print(res.eval())

with tf.Session() as sess:
    print(res.eval())

[[ 8  8]
 [18 18]]


In [49]:
var1 = tf.Variable(1221)
#print(var1)
var2 = tf.Variable(3)
addition = var1 + var2
sess = tf.Session()
sess.run(tf.global_variables_initializer())
#sess.run(var1.assign(1232))
assign_object = var1.assign(1232)
#sess.run(assign_object)
#addition = var1 + var2
sess.run(addition)

1224

In [66]:
x = tf.placeholder(tf.int32, shape=(2, None))
y = x * tf.constant(20)
print(y)
sess = tf.Session()
print(sess.run(y, feed_dict={x:[[1,2,3, 5],[4,5,6, 8]]}))
sess.run(y, feed_dict={x:[[10,20,30],[40,50,60]]})

Tensor("mul_14:0", shape=(2, ?), dtype=int32)
[[ 20  40  60 100]
 [ 80 100 120 160]]


array([[ 200,  400,  600],
       [ 800, 1000, 1200]], dtype=int32)